using UnityEditor;

namespace BHO.SceneReference.Editor
{
    public static class SceneRegistrySettings
    {
        private const string STORAGE_MODE_KEY = "BHO.SceneRegistry.StorageMode";

        public static StorageMode StorageMode
        {
            get => (StorageMode)EditorPrefs.GetInt(STORAGE_MODE_KEY, (int)StorageMode.AutoGenerated);
            set => EditorPrefs.SetInt(STORAGE_MODE_KEY, (int)value);
        }

        [SettingsProvider]
        public static SettingsProvider SceneRegistrySettingsProvider()
        {
            return new SettingsProvider("Project/Black Hole Odyssey/Scene Registry", SettingsScope.Project)
            {
                label = "Scene Registry",
                guiHandler = _ =>
                {
                    StorageMode = (StorageMode)EditorGUILayout.EnumPopup("Storage Mode", StorageMode);

                    if (StorageMode == StorageMode.StreamingAsset)
                    {
                        EditorGUILayout.HelpBox("The encryption key will be stored in a ScriptableObject and accessible in the build.",
                            MessageType.Warning);
                    }
                },
                keywords = new[] { "Scene", "Registry", "Storage" }
            };
        }
    }
}