using System.IO;
using UnityEditor;
using UnityEngine;

namespace BHO.SceneReference.Editor
{
    public static class SceneRegistrySettings
    {
        [SettingsProvider]
        public static SettingsProvider SceneRegistrySettingsProvider()
        {
            return new SettingsProvider("Project/Black Hole Odyssey/Scene Registry", SettingsScope.Project)
            {
                label = "Scene Registry",
                guiHandler = _ =>
                {
                    SceneRegistryConfig config = SceneRegistryConfig.Instance;
                    if (config == null) return;

                    SerializedObject serializedConfig = new SerializedObject(config);
                    serializedConfig.Update();

                    SerializedProperty storageModeProperty = serializedConfig.FindProperty("StorageMode");
                    SerializedProperty keyProperty = serializedConfig.FindProperty("customKey");
                    
                    EditorGUI.BeginChangeCheck();
                    EditorGUILayout.PropertyField(storageModeProperty, new GUIContent("Storage Mode"));
                    if (EditorGUI.EndChangeCheck())
                    {
                        serializedConfig.ApplyModifiedProperties();
                        EditorUtility.SetDirty(config);
        
                        if (config.StorageMode == StorageMode.AutoGenerated)
                        {
                            string jsonPath = Path.Combine(Application.streamingAssetsPath, "SceneRegistry.json");
                            if (File.Exists(jsonPath))
                            {
                                File.Delete(jsonPath);
                                File.Delete(jsonPath + ".meta");
                            }
                        }

                        SceneRegistrySaveSystem.ResetStorage();
                        SceneRegistrySaveSystem.Save(SceneRegistry.Scenes);
                        AssetDatabase.Refresh();
                    }
                    
                    if (config.StorageMode == StorageMode.StreamingAssets)
                    {
                        EditorGUI.BeginChangeCheck();
                        keyProperty.stringValue = EditorGUILayout.TextField("Custom Key", keyProperty.stringValue);
                        if (EditorGUI.EndChangeCheck())
                        {
                            serializedConfig.ApplyModifiedProperties();
                            EditorUtility.SetDirty(config);
                        }

                        if (GUILayout.Button("Apply Key"))
                        {
                            // 1. Supprimer l'ancien JSON chiffré avec l'ancienne clé
                            string jsonPath = Path.Combine(Application.streamingAssetsPath, "SceneRegistry.json");
                            if (File.Exists(jsonPath))
                            {
                                File.Delete(jsonPath);
                                File.Delete(jsonPath + ".meta");
                            }

                            // 2. Reset pour forcer la recréation avec la nouvelle clé
                            SceneRegistrySaveSystem.ResetStorage();
                            SceneRegistry.Reload();

                            // 3. Sauvegarder avec la nouvelle clé
                            SceneRegistrySaveSystem.Save(SceneRegistry.Scenes);
                            AssetDatabase.Refresh();
                        }

                        EditorGUILayout.HelpBox("The encryption key will be stored in a ScriptableObject and accessible in the build.", MessageType.Warning);
                    }
                },
                keywords = new[] { "Scene", "Registry", "Storage"
            }
            };
        }
    }
}