// Copyright (c) 2026 Black Hole Odyssey
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

namespace BHO.SceneReference
{
    public enum StorageMode
    {
        AutoGenerated,
        StreamingAssets
    }
}
