// Copyright (c) 2026 Black Hole Odyssey
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

using System.IO;
using UnityEditor;
using UnityEngine;

namespace BHO.SceneReference.Editor
{
    public static class SceneReferenceSettings
    {
        [SettingsProvider]
        public static SettingsProvider SceneRegistrySettingsProvider()
        {
            return new SettingsProvider("Project/Black Hole Odyssey/Scene Reference", SettingsScope.Project)
            {
                label = "Scene Reference",
                guiHandler = _ =>
                {
                    SceneRegistryConfig config = SceneRegistryConfig.Instance;
                    if (config == null)
                    {
                        EditorGUILayout.HelpBox("No SceneRegistryConfig found. Please create one via Create > BHO > Scene Registry Config.", MessageType.Warning);
                        return;
                    }

                    SerializedObject serializedConfig = new SerializedObject(config);
                    serializedConfig.Update();

                    SerializedProperty storageModeProperty = serializedConfig.FindProperty("StorageMode");
                    SerializedProperty keyProperty = serializedConfig.FindProperty("customKey");
                    
                    EditorGUI.BeginChangeCheck();
                    EditorGUILayout.PropertyField(storageModeProperty, new GUIContent("Storage Mode"));
                    
                    GUIStyle helpBoxStyle = new GUIStyle(EditorStyles.helpBox)
                    {
                        fontSize = 12,
                        wordWrap = true,
                        padding = new RectOffset(8, 8, 8, 8)
                    };
                    
                    if (EditorGUI.EndChangeCheck())
                    {
                        serializedConfig.ApplyModifiedProperties();
                        EditorUtility.SetDirty(config);
        
                        if (config.StorageMode == StorageMode.AutoGenerated)
                        {
                            string jsonPath = Path.Combine(Application.streamingAssetsPath, "SceneRegistry.json");
                            if (File.Exists(jsonPath))
                            {
                                File.Delete(jsonPath);
                                File.Delete(jsonPath + ".meta");
                            }
                        }

                        SceneRegistrySaveSystem.ResetStorage();
                        SceneRegistrySaveSystem.Save(SceneRegistry.Scenes);
                        AssetDatabase.Refresh();
                    }
                    
                    if (config.StorageMode == StorageMode.StreamingAssets)
                    {
                        EditorGUI.BeginChangeCheck();
                        keyProperty.stringValue = EditorGUILayout.TextField("Custom Key", keyProperty.stringValue);
                        if (EditorGUI.EndChangeCheck())
                        {
                            serializedConfig.ApplyModifiedProperties();
                            EditorUtility.SetDirty(config);
                        }

                        if (GUILayout.Button("Apply Key"))
                        {
                            string jsonPath = Path.Combine(Application.streamingAssetsPath, "SceneRegistry.json");
                            if (File.Exists(jsonPath))
                            {
                                File.Delete(jsonPath);
                                File.Delete(jsonPath + ".meta");
                            }
                            
                            SceneRegistrySaveSystem.ResetStorage();
                            SceneRegistry.Reload();
                            
                            SceneRegistrySaveSystem.Save(SceneRegistry.Scenes);
                            AssetDatabase.Refresh();
                        }

                        GUILayout.Label("StreamingAssets saves the registry in an encrypted JSON file accessible in the build files. This mode is intended for projects that need to update the registry without recompiling. In return, the encryption key is stored in a ScriptableObject that can be extracted from the build, making it less secure.", helpBoxStyle);
                    }
                    else
                    {
                        GUILayout.Label("Auto-Generated generates a C# file compiled directly into your build. This is the recommended mode: no external files, no encryption key, and the data is as protected as the rest of your code. It is possible to use this mode for DLC, but it also requires a game update since the auto-generated file will be recompiled with the new entries.", helpBoxStyle);
                    }
                },
                keywords = new[] { "Scene", "Registry", "Storage"
            }
            };
        }
    }
}